#!/bin/bash

. /HolismHolding/Infra/Scripts/CleanDocker.sh

function CreateSqlServerDatabaseContainer()
{
    ComposeFile=/Temp/$Organization/SqlDockerCompose.yml
    mkdir -p $(dirname $ComposeFile)
    envsubst < /HolismHolding/Infra/SqlServer/Dev/DockerCompose.yml > $ComposeFile
    docker-compose -p "${Organization}_Databases" -f $ComposeFile up --remove-orphans
}

function CreateMariaDbDatabaseContainer()
{
    ComposeFile=/Temp/$Organization/MaraiDbDockerCompose.yml
    mkdir -p $(dirname $ComposeFile)
    envsubst < /HolismHolding/Infra/MariaDb/Dev/DockerCompose.yml > $ComposeFile
    docker-compose -p "${Organization}_MaraiDb_Databases" -f $ComposeFile up --remove-orphans
}

function CreateDatabaseContainer()
{
    if [[ $(docker container ls | grep ${Organization}Databases) ]]; then
        # docker container stop ${Organization}Databases
        # CleanDocker
        return;
    fi
    CreateSqlServerDatabaseContainer
    CreateMariaDbDatabaseContainer
}