#!/bin/bash

. /HolismHolding/Infra/Scripts/CleanDocker.sh
. /HolismHolding/Infra/Scripts/Message.sh

function CreateSqlServerDatabaseContainer()
{
    Info 'Creating SQL Server container'
    ComposeFile=/Temp/$Organization/SqlDockerCompose.yml
    mkdir -p $(dirname $ComposeFile)
    envsubst < /HolismHolding/Infra/SqlServer/Dev/DockerCompose.yml > $ComposeFile
    docker-compose -p "${Organization}_Databases" -f $ComposeFile up --remove-orphans
}

function CreateMariaDbDatabaseContainer()
{
    Info 'Creating MariaDB container'
    ComposeFile=/Temp/$Organization/MariaDbDockerCompose.yml
    mkdir -p $(dirname $ComposeFile)
    envsubst < /HolismHolding/Infra/MariaDb/Dev/DockerCompose.yml > $ComposeFile
    docker-compose -p "${Organization}_MariaDb_Databases" -f $ComposeFile up --remove-orphans
}

function CreateDatabaseContainer()
{
    # if [[ $(docker container ls | grep ${Organization}Databases) ]]; then
    #     # docker container stop ${Organization}Databases
    #     # CleanDocker
    #     return;
    # fi
    Devide
    CreateSqlServerDatabaseContainer
    CreateMariaDbDatabaseContainer
    Devide
}