FROM mcr.microsoft.com/mssql/server:latest
ENV PATH="${PATH}:/root/.dotnet/tools:/HolismHolding/Infra/SqlServer/Dev"  
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=lksU2o412f7tBj58t07B
ENV MSSQL_PID=Express
USER root
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15

# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-get-started?view=sql-server-ver15