version: "3.9"
services: 
    accounts:
        image: jboss/keycloak:latest
        container_name: Accounts
        ports: 
            - "${RandomPort}:8080"
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=JNC1gcUVL9O6ZMxr7vKm
            - DB_VENDOR=mariadb
            - DB_ADDR=database
            - DB_DATABASE=accounts
            - DB_USER=keycloak
            - DB_PASSWORD=52wfDZSvFsfhC5tT3jW9
        volumes:
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /Temp/HolismHolding/Accounts:/Temp
    database:
        image: mariadb
        container_name: AccountsDatabase
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=2TBE9tN4Y5jM3Mvxjr5T
            - MYSQL_DATABASE=accounts
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=52wfDZSvFsfhC5tT3jW9
    pma:
        image: phpmyadmin:latest
        container_name: AccountsPma
        ports:
            - 3232:80
        environment: 
            - PMA_HOST=database
