version: "3.9"
services: 
    accounts:
        image: quay.io/keycloak/keycloak:14.0.0
        container_name: Accounts
        ports: 
            - "${RandomPort}:8080"
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR:mariadb
            - DB_ADDR:AccountsDatabase
            - DB_DATABASE:accounts
        volumes:
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /Temp/HolismHolding/Accounts:/Temp
    database:
        image: mariadb
        container_name: AccountsDatabase
        environment:
            - MYSQL_ROOT_PASSWORD:2TBE9tN4Y5jM3Mvxjr5T
            - MYSQL_DATABASE=accounts
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=52wfDZSvFsfhC5tT3jW9
