name: Build & push Docker image

on:
  schedule:
    - cron:  '30 7 * * *'
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:

      # Base

      - name: Get /HolismHolding/Infra
        run: |
          sudo mkdir /HolismHolding
          sudo chmod 777 /HolismHolding
          cd /HolismHolding
          git clone https://github.com/HolismHolding/Infra
          
      - name: Get /HolismReact/Infra
        run: |
          sudo mkdir /HolismReact
          sudo chmod 777 /HolismReact
          cd /HolismReact
          git clone https://github.com/HolismReact/Infra

      - name: Create /${Organization} directory
        run: |
          sudo mkdir /${Organization}
          sudo chmod 777 /${Organization}

      # DependenciesGettingDependencyRepositoriesPlacholder

      # Main
      GettingMainRepositoryPlaceholder
      BuildLoginPushLogout