#!/bin/bash

export Database=Logs

sudo mkdir -p /Temp/SchemaCompare/$Database

sqlpackage /a:extract /of:true /scs:"data source=localhost,1433; initial catalog=$Database; user id=SA; password=lksU2o412f7tBj58t07B;" /tf:"/Temp/SchemaCompare/$Database/Source.dacpac";

sqlpackage /a:deployreport /op:"/Temp/SchemaCompare/$Database/Report.xml" /of:True /sf:"/Temp/SchemaCompare/$Database/Source.dacpac" /tcs:"data source=$TargetServer; initial catalog=$Database; user id=SA; password=$TargetPassword;" /P:DropObjectsNotInSource=True 

sqlpackage /a:script /op:"/Temp/SchemaCompare/$Database/Migration.sql" /of:True /sf:"/Temp/SchemaCompare/$Database/Source.dacpac" /tcs:"data source=$TargetServer; initial catalog=Logs; user id=SA; password=$TargetPassword;" /P:DropObjectsNotInSource=True
