#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

if [ ! -f "$PWD/Dependencies" ]; then
    Error "Can't find the file Dependencies";
    exit;
fi

export TargetServer=$1

if [ ${TargetServer:-NotSet} == "NotSet" ]; then 
    Error "TargetServer is not provided";
    exit;
fi

export TargetPassword=$2

if [ ${TargetPassword:-NotSet} == "NotSet" ]; then 
    Error "TargetPassword is not provided";
    exit;
fi

sudo rm -rf /Temp/SchemaCompare

function Compare()
{
    sudo mkdir -p /Temp/SchemaCompare/$1
    sudo chmod -R 777 /Temp/SchemaCompare/$1

    sqlpackage /a:extract /of:true /scs:"data source=localhost,1433; initial catalog=$1; user id=SA; password=lksU2o412f7tBj58t07B;" /tf:"/Temp/SchemaCompare/$1/Source.dacpac";

    sqlpackage /a:deployreport /op:"/Temp/SchemaCompare/$1/Report.xml" /of:True /sf:"/Temp/SchemaCompare/$1/Source.dacpac" /tcs:"data source=$TargetServer; initial catalog=$1; user id=SA; password=$TargetPassword;" /P:DropObjectsNotInSource=True /P:DropPermissionsNotInSource=False /P:IgnorePermissions=True /mp:10

    sqlpackage /a:script /op:"/Temp/SchemaCompare/$1/Migration.sql" /of:True /sf:"/Temp/SchemaCompare/$1/Source.dacpac" /tcs:"data source=$TargetServer; initial catalog=$1; user id=SA; password=$TargetPassword;" /P:DropObjectsNotInSource=True /P:DropPermissionsNotInSource=False /P:IgnorePermissions=True /mp:10

    sudo chmod -R 777 /Temp/SchemaCompare
}

while read Dependency; do  
    
    Org=$(echo $Dependency | cut -d'/' -f1)
    Repo=$(echo $Dependency | cut -d'/' -f2)

    Info "Comparing $Repo ...";
    Compare $Repo
    
done <<< "$({ cat "$PWD/Dependencies"; echo; })"
