version: "3.9"
services: 
    react:
        image: holism/react-dev:latest
        container_name: ${Organization}${Repository}
        ports:
            - "$RandomPort:3000"
        working_dir: ${RepositoryPath}
        environment:
            - Organization=${Organization}
            - OrganizationPrefix=${OrganizationPrefix}
            - RepositoryPath=${RepositoryPath}
            - Repository=${Repository}
        volumes:
            - /HolismHolding:/HolismHolding
            - /HolismReact/Infra/src/index.css:${RepositoryPath}/src/index.css
            - /HolismReact/Infra/src/index.js:${RepositoryPath}/src/index.js
            - /HolismReact/Infra/src/Base:${RepositoryPath}/src/Base
            - /HolismReact/Infra/src/Panel:${RepositoryPath}/src/Panel
            - /HolismReact/Infra/src/Components:${RepositoryPath}/src/Components
            - /HolismReact/Infra/public/index.html:${RepositoryPath}/public/index.html
            - /HolismReact/Infra/public/robots.txt:${RepositoryPath}/public/robots.txt
            - /HolismReact/Infra/craco.config.js:${RepositoryPath}/craco.config.js
            - /HolismReact/Infra/tailwind.config.js:${RepositoryPath}/tailwind.config.js
            - /HolismReact/Infra/package.json:${RepositoryPath}/package.json
            - ${RepositoryPath}/Logo.js:${RepositoryPath}/src/Logo.js
            - ${RepositoryPath}/Favicon.ico:${RepositoryPath}/public/favicon.ico
            - ${RepositoryPath}:${RepositoryPath}/src/${Repository}
            - ${RepositoryPath}/.env:${RepositoryPath}/.env
            - ${RepositoryPath}/.env.production:${RepositoryPath}/.env.production
            - ${RepositoryPath}/HeaderActions.js:${RepositoryPath}/src/HeaderActions.js
            - ${RepositoryPath}/Menu.js:${RepositoryPath}/src/Menu.js
            - ${RepositoryPath}/Routes.js:${RepositoryPath}/src/Routes.jsVolumeMappingPlaceHolder
        #stdin_open: true # docker run -i
        #tty: true        # docker run -t
        command: >
            sh -c
            "
            cd ${RepositoryPath}
            && if [ ! -d ${RepositoryPath}/node_modules ]; then ln -s /HolismReact/Infra/node_modules ${RepositoryPath}; fi
            && echo -e '\033[0;31m'"http://localhost:$RandomPort" "http://$Host"
            && WatchForModification &
            npm start &
            tail -f /dev/null
            "