#!/bin/sh

inotifywait -m /HolismReact/ -r -e modify --format '%w%f' "$1" | 
while read File
do
    #echo "File $File is modified"
    find /$Organization/$Repository/ -type l | grep -v node_modules | grep -v .gitignore
    while read LinkedFile; do 
        OriginalPath=$(readlink -f $LinkedFile)
        #echo "$LinkedFile - $OriginalPath"
        if [ $OriginalPath = $File ]; then
            Temp=$(dirname $File)/wjagCcKD0uY859DianqQ.temp
            #echo 'equal';
            cp $File $Temp
            ln -s -f $Temp $LinkedFile
            ln -s -f $File $LinkedFile
            sudo rm -rf $Temp
        fi
    done
done
