#!/bin/bash

# build = deploy = publish

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/CreateTempDirectories.sh
. /HolismHolding/Infra/Scripts/GetHolismHoldingInfra.sh

. /HolismHolding/Infra/Next/IsNext.sh
. /HolismHolding/Infra/Next/Prod/Build.sh

. /HolismHolding/Infra/React/IsReact.sh
. /HolismHolding/Infra/React/Prod/Build.sh

. /HolismHolding/Infra/DotNet/IsDotNet.sh
. /HolismHolding/Infra/DotNet/Prod/Build.sh

. /HolismHolding/Infra/Vite/IsVite.sh
. /HolismHolding/Infra/Vite/Prod/Build.sh

# package & app = module & host = reusable & runnable

sudo echo ""
Info "Holding build"
if [ $PWD = '/' ]; then
    Error "You are in the root directory. Run Build from inside a project's directory.";
    exit;
fi
if ! (IsReact || IsNext || IsDotNet || IsVite); then
    Error "Project type = Unknown"
    exit 1
fi

ExtractAndExportData
CreateTempDirectories
GetHolismHoldingInfra

Dockerfile=/Build/Dockerfile
if IsNext $1; then
    BuildNext
elif IsVite $1; then
    BuildVite
elif IsReact $1; then
    BuildReact;
elif IsDotNet $1; then
    BuildDotNet
else
    Warning "Project type = Unknown"
fi

DockerImageName=ghcr.io/$LowercaseOrg/$LowercaseRepo:latest
if [[ $ParentOrganization != "" ]]; then
    DockerImageName=ghcr.io/$LowercaseParentOrg/${LowercaseOrg}/${LowercaseRepo}:latest
fi
docker build -f $Dockerfile -t $DockerImageName /Build

# sudo rm -rf /Build