#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/CreateTempDirectories.sh
. /HolismHolding/Infra/Scripts/GetHoldingInfra.sh
. /HolismHolding/Infra/React/IsReact.sh
. /HolismHolding/Infra/React/Build.sh
. /HolismHolding/Infra/DotNet/IsDotNet.sh
. /HolismHolding/Infra/DotNet/Prod/Build.sh

# package & app = module & host = reusable & runnable

echo "Holding build"
ExtractAndExportData
CreateTempDirectories

if IsReact $1; then
    BuildReact
# elif IsDotNet $1; then
#     BuildDotNet
else
    echo "Project type = Unknown"
fi