#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
cyan=`tput setaf 6`

ipS2=$1
passS2=$2

ipS1=$(hostname -I | cut -d' ' -f1)
passS1=$3

if [ ! -f "$PWD/Dependencies" ]; then
    echo -e '\033[0;31m'"Can't find the file Dependencies";
    return;
fi

while read Dependency; do  

    Repo=$(echo $Dependency | cut -d'/' -f2)
    echo "${cyan} ${Repo} ${reset}"
    docker run --rm --interactive     redgate/sqlcompare:14 /IAgreeToTheEULA     /s1:$ipS1 /db1:${Repo} /u1:SA /p1:$passS1     /s2:$ipS2 /db2:${Repo} /u2:SA /p2:$passS2

done <<< "$({ cat "$PWD/Dependencies"; echo; })"