#!/bin/bash
. /HolismHolding/Infra/Scripts/Message.sh

Organization=$1

if [[ $Organization == "" ]]; then 
    Error 'Organization name is not provided';
    exit;
fi

Info "Organization: $Organization"

sudo mkdir -p /$Organization
sudo chmod 777 /$Organization

cd /$Organization

export accessToken=$(cat /LocalSecrets/GitHubAccessToken)

curl --silent -H "Authorization: token $accessToken" "https://api.github.com/orgs/$Organization/repos" | jq -r ".[].name" | while read -r name ; do
    if [[ "$name" == *Api ]] || [[ "$name" == *Panel ]] || [[ "$name" == Site ]] || [[ "$name" == Common ]] || [[ "$name" == Blog ]]; then
        git clone git@github.com:$Organization/$name
    fi
done

sudo chmod -R 777 /$Organization 2>/dev/null