#!/bin/bash

Organization=$1

if [ ${Organization:-NotSet} == "NotSet" ]; then 
    echo 'Organization name is not provided';
    exit;
fi

echo "Organization: $Organization"

sudo mkdir -p /$Organization
sudo chmod 777 /$Organization

cd /$Organization

export accessToken=$(cat /LocalSecrets/GitHubAccessToken)

curl --silent -H "Authorization: token $accessToken" "https://api.github.com/orgs/$Organization/repos" | jq -r ".[].name" | while read -r name ; do
    if [[ "$name" == *Api ]] || [[ "$name" == *Panel ]] || [[ "$name" == Site ]] || [[ "$name" == Common ]] || [[ "$name" == Blog ]]; then
        git clone git@github.com:$Organization/$name
    fi
done

sudo chmod -R 777 /$Organization 2>&-