#!/bin/bash

Organization=$(basename $PWD)

echo "Organization: $Organization"

export accessToken=$(cat /LocalSecrets/GitHubAccessToken)

curl --silent -H "Authorization: token $accessToken" "https://api.github.com/orgs/$Organization/repos" | jq -r ".[].name" | while read -r name ; do
    if [[ "$name" == *Api ]] || [[ "$name" == *Panel ]]; then
        git clone git@github.com:$Organization/$name
    fi
done