#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/CreateTempDirectories.sh
. /HolismHolding/Infra/Scripts/GetHolismHoldingInfra.sh
. /HolismHolding/Infra/React/Site/IsReactSite.sh
. /HolismHolding/Infra/Next/Debug.sh
. /HolismHolding/Infra/DotNet/IsDotNet.sh
. /HolismHolding/Infra/DotNet/Debug/Debug.sh
. /HolismHolding/Infra/Scripts/GetRandomPort.sh
. /HolismHolding/Infra/Scripts/GetHost.sh
. /HolismHolding/Infra/Scripts/CreateCertificate.sh
. /HolismHolding/Infra/Scripts/SetupNginxAndLocalDns.sh
. /HolismHolding/Infra/Scripts/CleanDocker.sh

sudo echo "Start debug"
if ! (IsReactSite || IsDotNet); then
    echo "Project type = Unknown"
    exit 1
fi
export SelectedProject=$1
ExtractAndExportData
CreateTempDirectories &
GetHolismHoldingInfra &
GetRandomPort
GetHost
CreateCertificate
SetupNginxAndLocalDns &
CleanDocker

if IsReactSite $1; then
    DebugSite
elif IsDotNet $1; then
    DebugDotNet
else
    echo "Project type = Unknown"
fi