#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/CreateTempDirectories.sh
. /HolismHolding/Infra/Scripts/GetHolismHoldingInfra.sh
. /HolismHolding/Infra/Scripts/GetRandomPort.sh
. /HolismHolding/Infra/Scripts/GetHost.sh
. /HolismHolding/Infra/Scripts/CreateCertificate.sh
. /HolismHolding/Infra/Scripts/SetupNginxAndLocalDns.sh
. /HolismHolding/Infra/Scripts/CleanDocker.sh

. /HolismHolding/Infra/Next/IsNext.sh
. /HolismHolding/Infra/Next/Debug/Debug.sh
. /HolismHolding/Infra/DotNet/IsDotNet.sh
. /HolismHolding/Infra/DotNet/Debug/Debug.sh

sudo echo "Start debug"
if ! (IsNext || IsDotNet); then
    echo "Project type = Unknown"
    exit 1
fi
export SelectedProject=$1
ExtractAndExportData
CreateTempDirectories &
GetHolismHoldingInfra &
GetRandomPort
GetHost
CreateCertificate
SetupNginxAndLocalDns &
CleanDocker

if IsNext $1; then
    DebugNext
elif IsDotNet $1; then
    DebugDotNet
else
    echo "Project type = Unknown"
fi