#!/bin/bash

docker stats --no-stream | awk '/SadraTrade/  {print $3, $4, $8, $11}' | xargs awk '{
    for (i=2; i<=NF; i++) {
        sumcols[i]+= $i; sumrows+= $i 
    }; print $0, sumrows
}
END { for (x in sumcols)
         { printf SEP sumcols[x]; SEP=FS };
     print ""
}' infile
