#!/bin/bash

# /Temp/Organizations => a file containing organization names line by line

# /HolismHolding/Server/Scripts/DockerAwk.sh => the command here:
# https://unix.stackexchange.com/questions/688228/how-to-group-docker-stats-by-container-name-prefix

echo "RAM CPU Network IO"

docker stats --no-stream | awk -f /HolismHolding/Server/Scripts/DockerAwk.sh /Temp/Organizations -