#!/bin/bash

# /temp/l => a file containing organization names line by line

# /temp/awk.txt => the command here:
# https://unix.stackexchange.com/questions/688228/how-to-group-docker-stats-by-container-name-prefix

docker stats --no-stream | awk -f /Temp/awk.txt /Temp/l -