#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

find / -type d -name .git 2>/dev/null | 
{
    while read gitFolder; do
        if [[ $gitFolder == *"/Temp/"* ]]; then
            continue;
        fi
        if [[ $gitFolder == *"/Trash/"* ]]; then
            continue;
        fi
        if [[ $gitFolder == *"/opt/"* ]]; then
            continue;
        fi
        parent=$(dirname $gitFolder);
        if [ $(ls $parent -A | wc -l ) == 1 ]; then
            echo $parent
        fi
    done 
}
