#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

Info 'Getting the current status ...'
GitStatus

echo
echo
Warning 'Still pushing? (y,n)'
read Consent

if [ $Consent != 'y' ]; then
    exit;
fi

find / -type d -name .git 2>/dev/null | 
{
    while read gitFolder; do
        if [[ $gitFolder == *"/Temp/"* ]]; then
            continue;
        fi
        if [[ $gitFolder == *"/Trash/"* ]]; then
            continue;
        fi
        if [[ $gitFolder == *"/opt/"* ]]; then
            continue;
        fi
        parent=$(dirname $gitFolder);
        if [[ `git -C $parent status --porcelain` ]]; then
            echo "";
            (
                Info $parent;
                git -C $parent status --porcelain
                git -C $parent add .
                git -C $parent commit -m "committed by script"
                git -C $parent push
            ) &
        fi
    done
    wait
}
Divide
Success "Pushed all"
Divide
