#!/bin/bash

echo 'Getting the current status ...'
GitStatus

echo
echo
echo 'Still pushing? (y,n)'
read Consent

if [ $Consent != 'y' ]; then
    exit;
fi

find / -type d -name .git 2>&- | 
while read gitFolder; do
    if [[ $gitFolder == *"/Temp/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/Trash/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/opt/"* ]]; then
        continue;
    fi
    parent=$(dirname $gitFolder);
    if [[ `git -C $parent status --porcelain` ]]; then
        echo "";
        echo $parent;
        git -C $parent status --porcelain
        git -C $parent add .
        git -C $parent commit -m "committed by script"
        git -C $parent push
    fi
done