#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

echo
Warning 'All of your local changes will be deleted permanentaly.'
Warning 'Are you sure you want to reset? (y,n)'
read Consent

if [ $Consent != 'y' ]; then
    exit;
fi

find / -type d -name .git 2>/dev/null | 
while read gitFolder; do
    if [[ $gitFolder == *"/Temp/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/Trash/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/opt/"* ]]; then
        continue;
    fi
    parent=$(dirname $gitFolder);
    echo "";
    echo $parent;
    git -C $parent reset --hard && git -C $parent clean -fxd && echo "Reset $parent is done" &
done 

# https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find