#!/bin/bash

find / -type d -name .git 2>&- | 
while read gitFolder; do
    if [[ $gitFolder == *"/Temp/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/Trash/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/opt/"* ]]; then
        continue;
    fi
    parent=$(dirname $gitFolder);
    # echo $parent
    if [[ `git -C $parent status --porcelain` ]]; then
        echo "";
        echo $parent;
        git -C $parent status --porcelain
    elif [[ $(git -C $parent status | grep ahead) ]]; then
        echo "";
        echo "Push $parent";
    elif [[ $(git -C $parent status | grep diverged) ]]; then
        echo "";
        echo "Sync $parent";
    fi
done 

# https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find