#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

Organization=$1

if [ ${Organization:-NotSet} == "NotSet" ]; then 
    echo 'Organization name is not provided';
    exit;
fi

echo "Organization: $Organization"

export accessToken=$(cat /LocalSecrets/GitHubAccessToken)

curl --silent -H "Authorization: token $accessToken" "https://api.github.com/orgs/$Organization/repos" | jq -r ".[].name" | while read -r name ; do
    if [[ "$name" == *Api ]] || [[ "$name" == *Panel ]] || [[ "$name" == Site ]]; then
        Info "Running action of $name"

        curl \
            -H "Accept: application/vnd.github.v3+json"  \
            -H "Authorization: token $accessToken" \
            --request POST \
            "https://api.github.com/repos/$Organization/$name/actions/workflows/BuildAndPushDockerImage.yml/dispatches" \
            --data '{"ref": "master"}'

    fi
done