#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/CreateTempDirectories.sh
. /HolismHolding/Infra/Scripts/GetHolismHoldingInfra.sh
. /HolismHolding/Infra/Scripts/GetRandomPort.sh
. /HolismHolding/Infra/Scripts/GetHost.sh
. /HolismHolding/Infra/Scripts/CreateCertificate.sh
. /HolismHolding/Infra/Scripts/SetupNginxAndLocalDns.sh
. /HolismHolding/Infra/Scripts/CleanDocker.sh

. /HolismHolding/Infra/React/IsReact.sh
. /HolismHolding/Infra/React/Dev/Setup.sh

. /HolismHolding/Infra/Next/IsNext.sh
. /HolismHolding/Infra/Next/Dev/Setup.sh

. /HolismHolding/Infra/DotNet/IsDotNet.sh
. /HolismHolding/Infra/DotNet/Dev/Setup.sh

# package & app = module & host = reusable & runnable

sudo echo "Holding setup"
if [ $PWD = '/' ]; then
    echo "You are in the root directory. Run Setup from inside a project's directory.";
    exit;
fi
if ! (IsReact || IsNext || IsDotNet); then
    echo "Project type = Unknown"
    exit 1
fi
ExtractAndExportData
CreateTempDirectories &
GetHolismHoldingInfra &
GetRandomPort
GetHost
CreateCertificate
SetupNginxAndLocalDns &
CleanDocker

if IsNext $1; then
    SetupNext
elif IsReact $1; then
    SetupReact;
elif IsDotNet $1; then
    SetupDotNet
else
    echo "Project type = Unknown"
fi