#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/CreateTempDirectories.sh
. /HolismHolding/Infra/Scripts/GetHolismHoldingInfra.sh
. /HolismHolding/Infra/Scripts/GetHolismHoldingPolicies.sh
. /HolismHolding/Infra/Scripts/GetRandomPort.sh
. /HolismHolding/Infra/Scripts/GetHost.sh
. /HolismHolding/Infra/Scripts/CreateCertificate.sh
. /HolismHolding/Infra/Scripts/SetupNginxAndLocalDns.sh
. /HolismHolding/Infra/Scripts/CleanDocker.sh
. /HolismHolding/Infra/Scripts/Message.sh

. /HolismHolding/Infra/DotNet/IsDotNet.sh
. /HolismHolding/Infra/Next/IsNext.sh
. /HolismHolding/Infra/Vite/IsVite.sh

. /HolismHolding/Infra/DotNet/Dev/Setup.sh
. /HolismHolding/Infra/Next/Dev/Setup.sh
. /HolismHolding/Infra/Vite/Dev/Setup.sh

# package & app = module & host = reusable & runnable
sudo echo ""
Info "Holding setup"
if [ $PWD = '/' ]; then
    Error "You are in the root directory. Run Setup from inside a project's directory.";
    exit;
fi
if ! (IsNext || IsDotNet || IsVite); then
    Error "Project type = Unknown"
    exit 1
fi
ExtractAndExportData
CreateTempDirectories &
# GetHolismHoldingInfra &
# GetHolismHoldingPolicies &
GetRandomPort
GetHost
CreateCertificate
SetupNginxAndLocalDns &
CleanDocker

sudo chmod -R 777 /$Organization

if IsNext $1; then
    SetupNext
elif IsVite $1; then
    SetupVite
elif IsDotNet $1; then
    SetupDotNet
else
    Warning "Project type = Unknown"
fi