#!/bin/bash
. /HolismHolding/Infra/Scripts/Message.sh

Organization=$1

if [[ $Organization == "" ]]; then 
    Error 'Organization name is not provided';
    exit;
fi

sudo echo ""
Info "Organization: $Organization"

docker stop $(docker ps -aq)
docker container prune --force
docker rm -vf $(docker ps -a -q)
docker system prune -y

cd /$Organization

ls | while read -r name ; do
    if [[ "$name" == *Api ]] || [[ "$name" == *Panel ]] || [ "$name" == Site ]  || [ "$name" == Blog ]; then
       cd /$Organization/$name;
       Setup &
    fi
done