#!/bin/bash

. /HolismHolding/Infra/Scripts/GetRandomPort.sh
. /HolismHolding/Infra/Scripts/SetupNginxAndLocalDns.sh

export Organization="HolismHolding"
export OrganizationPrefix="Holism";
export Repository="Accounts"
export RepositoryPath="HolismHolding/Accounts"
export LowercaseOrg="holism"
export LowercaseRepo="accounts"
echo "Organization: " $Organization
echo "Organization Prefix: " $OrganizationPrefix
echo "Repository: " $Repository

GetRandomPort
SetupNginxAndLocalDns
ComposeFile=/Temp/HolismAccounts/Accounts/Runnable.yml
mkdir -p $(dirname $ComposeFile)
envsubst < /HolismHolding/Infra/Accounts/Runnable.yml > $ComposeFile
docker-compose -p "Holism_Accounts" -f $ComposeFile up --remove-orphans