#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

echo

find / -type d -name .git 2>/dev/null | 
while read gitFolder; do
    if [[ $gitFolder == *"/Temp/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/Trash/"* ]]; then
        continue;
    fi
    if [[ $gitFolder == *"/opt/"* ]]; then
        continue;
    fi
    parent=$(dirname $gitFolder);

    if [[ `git -C $parent status --porcelain` ]]; then
        Info $parent;
        git -C $parent status --porcelain
        if [ -d /HolismHolding/Policies ]; then
            /HolismHolding/Policies/Run.sh $parent
        fi
        Divide
    elif [[ $(git -C $parent status | grep ahead) ]]; then
        Warning "Push $parent";
        Divide
    elif [[ $(git -C $parent status | grep diverged) ]]; then
        Warning "Sync $parent";
        Divide
    fi
done 

# https://stackoverflow.com/questions/9612090/how-to-loop-through-file-names-returned-by-find