name: Build & push Docker image

on:
  schedule:
    - cron:  '30 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Base

      - name: Get /HolismHolding/Infra
        run: |
          sudo mkdir /HolismHolding
          sudo chmod -R 777 /HolismHolding
          cd /HolismHolding
          git clone https://github.com/HolismHolding/Infra

      - name: Create /${Organization} directory
        run: |
          sudo mkdir /${Organization}
          sudo chmod 777 /${Organization}

      # Main
      GettingMainRepositoryPlaceholder
      BuildLoginPushLogout