#!/bin/bash

. /HolismHolding/Infra/Scripts/CleanDocker.sh
. /HolismHolding/Infra/Scripts/Message.sh
. /HolismHolding/Infra/Scripts/SetupNginxAndLocalDns.sh
. /HolismHolding/Infra/Scripts/GetRandomPort.sh
. /HolismHolding/Infra/Scripts/CreateCertificate.sh

function GetOrganizationDatabaseHost()
{
    IFS='.' read -r -a array <<< $(cat Host)
    hostIndex=$(( ${#array[@]} - 2 ))
    hostArray=(${array[@]:$hostIndex:2})
    export Host=db.${hostArray[0]}.${hostArray[1]}
}

function CreateMariaDatabaseContainer()
{
    Info 'Creating MariaDB container'
    ComposeFile=/Temp/$Organization/Databases/DockerCompose.yml
    mkdir -p $(dirname $ComposeFile)
    sudo chmod 777 $(dirname $ComposeFile)
    sudo rm -rf $ComposeFile
    envsubst < /HolismHolding/Infra/Maria/Dev/DockerCompose.yml > $ComposeFile
    docker-compose -p "${Organization}Databases" -f $ComposeFile up -d --remove-orphans
}

function CreateDatabaseContainer()
{
    GetOrganizationDatabaseHost

    OriginalRepository=$Repository
    Repository=Databases
    OriginalRandomPort=$RandomPort
    GetRandomPort
    export MariaPort=$RandomPort
    GetRandomPort
    export AdminerPort=$RandomPort

    CreateCertificate
    SetupNginxAndLocalDns

    Repository=$OriginalRepository
    RandomPort=$OriginalRandomPort
    
    Divide
    CreateMariaDatabaseContainer
    Divide
}