#!/bin/bash

. /HolismHolding/Infra/Scripts/CleanDocker.sh
. /HolismHolding/Infra/Scripts/Message.sh

function GetOrganizationDatabaseHost()
{
    IFS='.' read -r -a array <<< $(cat Host)
    hostIndex=$(( ${#array[@]} - 2 ))
    hostArray=(${array[@]:$hostIndex:2})
    export Host=db.${hostArray[0]}.${hostArray[1]}
}

function CreateMariaDatabaseContainer()
{
    Info 'Creating MariaDB container'
    ComposeFile=/Temp/$Organization/MariaDockerCompose.yml
    mkdir -p $(dirname $ComposeFile)
    envsubst < /HolismHolding/Infra/Maria/Dev/DockerCompose.yml > $ComposeFile
    docker-compose -p "${Organization}Databases" -f $ComposeFile up --remove-orphans
}

function CreateDatabaseContainer()
{
    GetOrganizationDatabaseHost
    Divide
    #CreateMariaDatabaseContainer
    Divide
}

GetOrganizationDatabaseHost