#!bin/bash

export Organization=X
cd /
mkdir /$Organization
chmod 777 /$Organization
cd /$Organization
mkdir Accounts
chmod 777 Accounts
cd /Accounts
mkdir Databases
chmod 777 Databases
cd /$Organization
# loop over all roles (passed as argument) and build Panel and Api for each one of them
# and then create nginx's domain.conf, docker-compose.yml, Run and Stop commands for them