#!/bin/bash

function LinkLocalSecrets()
{
    if [ ! -d "/LocalSecrets" ]; then
        sudo mkdir /LocalSecrets
    fi
    sudo chmod -R 777 /LocalSecrets
    if [ ! -f "/LocalSecrets/$Organization.json" ]; then
        echo "{}" >> "/LocalSecrets/$Organization.json"
    fi
    sudo chmod 777 "/LocalSecrets/$Organization.json"
    echo "Linking LocalSecrets.json ...";
    sudo ln -s -f "/LocalSecrets/$Organization.json" "/$Organization/$Repository/LocalSecrets.json"
}