#!/bin/bash

function LinkLocalSecrets()
{
    if [ ! -d "/LocalSecrets" ]; then
        sudo mkdir /LocalSecrets
    fi
    sudo chmod -R 777 /LocalSecrets
    if [ ! -f "/LocalSecrets/$Organization.json" ]; then
        echo "{}" >> "/LocalSecrets/$Organization.json"
    fi
    sudo chmod 777 "/LocalSecrets/$Organization.json"
    if [ ! -f "/$Organization/$Repository/LocalSecrets.json" ]; then
        echo "Linking LocalSecrets.json ...";
        sudo ln -s "/LocalSecrets/$Organization.json" "/$Organization/$Repository/LocalSecrets.json"
    fi
}