version: "3.9"
services: 
    site:
        image: holism/next-dev:latest
        container_name: ${Organization}${Repository}
        ports:
            - "${RandomPort}:3000"
        working_dir: ${RepositoryPath}
        volumes: 
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /HolismReact/Site:/HolismReact/Site
            - ${RepositoryPath}/components:${RepositoryPath}/components
            - ${RepositoryPath}/contents:${RepositoryPath}/contents
            - ${RepositoryPath}/pages:${RepositoryPath}/pages
            - ${RepositoryPath}/public:${RepositoryPath}/public
            - ${RepositoryPath}/styles:${RepositoryPath}/styles
            - ${RepositoryPath}/.env:${RepositoryPath}/.env
            - /Temp${RepositoryPath}/Build:${RepositoryPath}/.next
        command: >
            sh -c
            "
            cp -a /HolismReact/Site/. .
            && if [ ! -d ${RepositoryPath}/node_modules ]; then ln -s /site/node_modules ${RepositoryPath}; fi
            && npm run dev &
            echo -e '\033[0;31m'"http://localhost:$RandomPort"
            && tail -f /dev/null
            "