FROM mcr.microsoft.com/mssql/server:latest
ENV PATH="${PATH}:/root/.dotnet/tools:/HolismHolding/Infra/SqlServer"  
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=lksU2o412f7tBj58t07B
ENV MSSQL_PID=Express
USER root
