version: "3.9"
services: 
    api:
        image: holism/dotnet-debug:latest
        #restart: always
        container_name: ${Organization}${Repository}
        working_dir: ${RepositoryPath}
        environment:
            - Organization=${Organization}
            - OrganizationPrefix=${OrganizationPrefix}
            - RepositoryPath=${RepositoryPath}
            - Repository=${Repository}
            - Host=${Host}
            - SqlServerPassword=wAv7tvFrYbDX8v8mYe1K
        volumes: 
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /HolismDotNet/Framework:/HolismDotNet/Framework
            - /FreyaCenter/OwnerApi:/FreyaCenter/OwnerApi
            - /HolismDotNet/Accounts:/HolismDotNet/Accounts
            - /HolismDotNet/Configuration:/HolismDotNet/Configuration
            - /HolismDotNet/Geo:/HolismDotNet/Geo
            - /HolismDotNet/Ticketing:/HolismDotNet/Ticketing
            - /FreyaCenter/Services:/FreyaCenter/Services
            - /FreyaCenter/Hr:/FreyaCenter/Hr
            - /FreyaCenter/Salons:/FreyaCenter/Salons
            - /FreyaCenter/Customers:/FreyaCenter/Customers
            - /FreyaCenter/Faker:/FreyaCenter/Faker
            - /FreyaCenter/Total:/FreyaCenter/Total
            - /FreyaCenter/Appointments:/FreyaCenter/Appointments
        ports: 
            - "$RandomPort:5000"
        command: >
            sh -c
            "
            dotnet build
            & echo -e '\033[0;31m'"http://localhost:$RandomPort" "http://$Host"
            & /HolismHolding/Infra/DotNet/Dev/SetupContainer.sh ${RepositoryPath} 
            && tail -f /dev/null
            "
        depends_on: 
            - "database"
        stdin_open: true # docker run -i
        tty: true  # docker run -t
    database:
        image: mcr.microsoft.com/mssql/server
        #restart: always
        user: root
        container_name: ${Organization}${Repository}Database
        volumes:
            - /HolismHolding/Infra/DotNet/Dev/Database:/Temp
            - /Temp/${Organization}/Database:/var/opt/mssql/data
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lksU2o412f7tBj58t07B
            - MSSQL_PID=Express
            - Repository=${Repository}
        ports:
            - 1433:1433
        logging:
            driver: none
        command: >
            sh -c
            "
            /Temp/SetupContainer.sh &
            /opt/mssql/bin/sqlservr
            "