version: "3.9"
services: 
    api:
        image: holism/dotnet-debug:latest
        #restart: always
        container_name: ${Organization}${Repository}
        working_dir: ${RepositoryPath}/${SelectedProject}
        environment:
            - Organization=${Organization}
            - OrganizationPrefix=${OrganizationPrefix}
            - RepositoryPath=${RepositoryPath}
            - Repository=${Repository}
            - SelectedProject=${SelectedProject}
            - Host=${Host}
            - SqlServerPassword=wAv7tvFrYbDX8v8mYe1K
        volumes: 
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /LocalSecrets:/LocalSecrets
            - /HolismDotNet/Infra:/HolismDotNet/InfraVolumeMappingPlaceHolder
        ports: 
            - "$RandomPort:5000"
        command: >
            sh -c
            "
            rm -rf ${SelectedProject}/bin
            && rm -rf ${SelectedProject}/obj
            && echo SelectedProjetc: ${SelectedProject}
            && dotnet build ${SelectedProject}
            & echo -e '\033[0;31m'"http://localhost:$RandomPort" "http://$Host"
            && tail -f /dev/null
            "
        stdin_open: true # docker run -i
        tty: true  # docker run -t
        networks:
            - ${Organization}Network
networks:
    ${Organization}Network:
        name: ${Organization}Network
        driver: bridge