version: "3.9"
services: 
    api:
        image: holism/dotnet-dev:latest
        #restart: always
        container_name: ${Organization}${Repository}
        working_dir: ${RepositoryPath}
        environment:
            - Organization=${Organization}
            - OrganizationPrefix=${OrganizationPrefix}
            - RepositoryPath=${RepositoryPath}
            - Repository=${Repository}
            - SqlServerPassword=wAv7tvFrYbDX8v8mYe1K
        volumes: 
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /HolismDotNet/Infra:/HolismDotNet/Infra
            - ${RepositoryPath}:${RepositoryPath}VolumeMappingPlaceHolder
        ports: 
            - "$RandomPort:5000"
        command: >
            sh -c
            "
            rm -rf Api/bin
            && rm -rf Api/obj
            && dotnet build
            && dotnet Api/bin/${OrganizationPrefix}.${Repository}.Api.dll &
            /HolismHolding/Infra/DotNet/Dev/SetupContainer.sh ${RepositoryPath} &
            echo -e '\033[0;31m'"http://localhost:$RandomPort" "http://$Host"
            && tail -f /dev/null
            "
        depends_on: 
            - "database"
        stdin_open: true # docker run -i
        tty: true  # docker run -t
    database:
        image: mcr.microsoft.com/mssql/server
        #restart: always
        user: root
        container_name: ${Organization}${Repository}Database
        volumes:
            - /HolismHolding/Infra/DotNet/Dev/Database:/Temp
            - /Temp/${Organization}/Database:/var/opt/mssql/data
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lksU2o412f7tBj58t07B
            - MSSQL_PID=Express
            - Repository=${Repository}
        ports:
            - 1433:1433
        logging:
            driver: none
        command: >
            sh -c
            "
            /Temp/SetupContainer.sh &
            /opt/mssql/bin/sqlservr
            "    
    mariaDb:
        image: mariadb
        container_name: ${Organization}${Repository}MariaDb
        ports:
            - 3306:3306
        logging:
            driver: none
        environment:
            - MARIADB_ROOT_PASSWORD=2TBE9tN4Y5jM3Mvxjr5T
            - MYSQL_DATABASE=accounts
            - MYSQL_USER=7F35e1j72wqJ53Cx22WU
            - MYSQL_PASSWORD=52wfDZSvFsfhC5tT3jW9
        volumes:
            - /HolismHolding/Infra/DotNet/Dev/MariaDb:/Temp
            - /Temp/${Organization}/MariaDb:/var/lib/mysql