#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/Message.sh

export ApiOrganization=$Organization
export ApiRepository=$Repository

Name=$1

if [[ $Name == "" ]]; then 
    ExtractAndExportData
else
    find / -type d -name $Name 2>/dev/null |
    while read dir;
    do
        if [ -f $dir/Database.json ]; then
            cd $dir
            Generate
        fi
    done
fi

if [ ! -f "$PWD/Database.json" ]; then
    Warning "Did not found Database.json";
    exit;
fi

export Directory=$PWD

cp /HolismHolding/Infra/DotNet/Dev/GitIgnore /HolismDotNet/Generation/.git/info/exclude
if [ -z ${IsBuilt+x} ]; then
    dotnet build /HolismDotNet/Generation
    chmod -R 777 /HolismDotNet/Generation
fi

cp /$ApiOrganization/$ApiRepository/ConnectionStrings.json /HolismDotNet/Generation/bin

cd /HolismDotNet/Generation

dotnet run $Directory $Organization $OrganizationPrefix $Repository

prompt=$(sudo -nv 2>&1)
if [ $? -eq 0 ]; then
    sudo chmod -R 777 $Directory
elif echo $prompt | grep -q '^sudo:'; then
    sudo chmod -R 777 $Directory
else
    chmod -R 777 $Directory
fi

Migrate
