#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/Message.sh

export ApiOrganization=$Organization
export ApiRepository=$Repository

ExtractAndExportData

if [ ! -f "$PWD/Database.json" ]; then
    Warning "Did not found Database.json";
    exit;
fi

if [ ! -d "$PWD/Models" ] || [ ! -d "$PWD/DataAccess" ]; then
    Warning "You should run this command inside a module, that has Models and DataAccess projects.";
    exit;
fi

export Directory=$PWD

if [ -z ${IsBuilt+x} ]; then
    dotnet build /HolismDotNet/Generation
    chmod -R 777 /HolismDotNet/Generation
fi

cp /$ApiOrganization/$ApiRepository/ConnectionStrings.json /HolismDotNet/Generation/bin

cd /HolismDotNet/Generation

dotnet run $Directory $Organization $OrganizationPrefix $Repository

prompt=$(sudo -nv 2>&1)
if [ $? -eq 0 ]; then
    sudo chmod -R 777 $Directory
elif echo $prompt | grep -q '^sudo:'; then
    sudo chmod -R 777 $Directory
else
    chmod -R 777 $Directory
fi

if [ -z ${IsBuilt+x} ]; then
    dotnet build /HolismDotNet/Generation
    chmod -R 777 /HolismDotNet/Generation
fi
