#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/Message.sh

ExtractAndExportData

if [ ! -f "$PWD/Dependencies" ]; then
    Error "Can't find the file Dependencies";
    exit;
fi

cp /HolismHolding/Infra/DotNet/Dev/GitIgnore /HolismDotNet/Generation/.git/info/exclude
dotnet build /HolismDotNet/Generation
chmod -R 777 /HolismDotNet/Generation
export IsBuilt=1;

while read Dependency; do  
    Info "${Org}/${Repo}"
    Org=$(echo $Dependency | cut -d'/' -f1)
    Repo=$(echo $Dependency | cut -d'/' -f2)

    if [ ! -f "/$Org/$Repo/Database.json" ]; then
        Warning "Did not found Database.json for $Org/$Repo";
    else 
        cd /$Org/$Repo
        Generate
    fi
done <<< "$({ cat "$PWD/Dependencies"; echo; })"

Migrate