#!/bin/bash

. /HolismHolding/Infra/Scripts/Message.sh

cp /HolismHolding/Infra/DotNet/Dev/GitIgnore /HolismDotNet/Query/.git/info/exclude
if [ -z ${IsBuilt+x} ]; then
    dotnet build /HolismDotNet/Query
    chmod -R 777 /HolismDotNet/Query
fi

cp /$Organization/$Repository/ConnectionStrings.json /HolismDotNet/Query/bin

cd /HolismDotNet/Query
