#!/bin/bash

. /HolismHolding/Infra/Scripts/ExtractAndExportData.sh
. /HolismHolding/Infra/Scripts/Message.sh

export ApiOrganization=$Organization
export ApiRepository=$Repository

ExtractAndExportData

export Directory=$PWD

cp /HolismHolding/Infra/DotNet/Dev/GitIgnore /HolismDotNet/Query/.git/info/exclude
if [ -z ${IsBuilt+x} ]; then
    dotnet build /HolismDotNet/Query
    chmod -R 777 /HolismDotNet/Query
fi

cp /$ApiOrganization/$ApiRepository/ConnectionStrings.json /HolismDotNet/Query/bin

cd /HolismDotNet/Query
