version: "3.9"
services: 
    api:
        image: holism/dotnet-dev:latest
        #restart: always
        container_name: ${Repository}DotNetApi
        working_dir: ${RepositoryPath}
        environment:
            - Organization=${Organization}
            - OrganizationPrefix=${OrganizationPrefix}
            - RepositoryPath=${RepositoryPath}
            - Repository=${Repository}
        volumes: 
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /HolismDotNet/Framework:/HolismDotNet/Framework
            - ${RepositoryPath}:${RepositoryPath}
        ports: 
            - "5000:5000"
        command: >
            sh -c
            "
            dotnet build
            && /HolismHolding/Infra/DotNet/Dev/SetupContainer.sh ${RepositoryPath}
            && dotnet Api/bin/${OrganizationPrefix}.${Repository}.Api.dll &
            tail -f /dev/null
            "
        depends_on: 
            - "database"
        stdin_open: true # docker run -i
        tty: true  # docker run -t
    database:
        image: mcr.microsoft.com/mssql/server
        #restart: always
        user: root
        container_name: ${Repository}MsSqlDatabase
        volumes:
            - /HolismHolding/Infra/DotNet/Dev/Database:/Temp
            - ./Database:/Database
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lksU2o412f7tBj58t07B
            - MSSQL_PID=Express
            - Repository=${Repository}
        ports:
            - 1433:1433
        logging:
            driver: none
        command: >
            sh -c
            "
            /Temp/SetupContainer.sh &
            /opt/mssql/bin/sqlservr
            "