version: "3.9"
services: 
    api:
        image: holism/dotnet-dev:latest
        #restart: always
        container_name: ${Organization}${Repository}
        working_dir: ${RepositoryPath}
        environment:
            - Organization=${Organization}
            - OrganizationPrefix=${OrganizationPrefix}
            - RepositoryPath=${RepositoryPath}
            - Repository=${Repository}
        volumes: 
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /HolismDotNet/Framework:/HolismDotNet/Framework
            - ${RepositoryPath}:${RepositoryPath}VolumeMappingPlaceHolder
        ports: 
            - "$RandomPort:5000"
        command: >
            sh -c
            "
            dotnet build
            && /HolismHolding/Infra/DotNet/Dev/SetupContainer.sh ${RepositoryPath} &
            dotnet Api/bin/${OrganizationPrefix}.${Repository}.Api.dll &
            echo -e '\033[0;31m'"http://localhost:$RandomPort" "http://$Host"
            && tail -f /dev/null
            "
        depends_on: 
            - "database"
        stdin_open: true # docker run -i
        tty: true  # docker run -t
    database:
        image: mcr.microsoft.com/mssql/server
        #restart: always
        user: root
        container_name: ${Organization}${Repository}Database
        volumes:
            - /HolismHolding/Infra/DotNet/Dev/Database:/Temp
            - /Temp/${Organization}/Database:/var/opt/mssql/data
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=lksU2o412f7tBj58t07B
            - MSSQL_PID=Express
            - Repository=${Repository}
        ports:
            - 1433:1433
        logging:
            driver: none
        command: >
            sh -c
            "
            /Temp/SetupContainer.sh &
            /opt/mssql/bin/sqlservr
            "