#!/bin/bash

function UpdateDatabase() {
    dotnet build /HolismDotNet/Framework/DatabaseUpdater

    find . -name "*.json" 2>&- | grep Database |
    while read databaseJson; do
        database=$(basename $databaseJson .json);
        echo "Updating database for $database";
        dotnet /HolismDotNet/Framework/DatabaseUpdater/bin/Holism.DatabaseUpdater.dll $PWD $databaseJson &
    done 
    echo -e '\033[0;31m'"Wait for all responses! They will be shown, though this command seems to be finished";
}

UpdateDatabase