#!/bin/bash

function UpdateDatabase() {
    dotnet build $PWD
    dotnet build /HolismDotNet/Infra/DatabaseGenerator
    cp $PWD/ConnectionStrings.json /HolismDotNet/Infra/DatabaseGenerator/bin

    find . -name "*.json" 2>&- | grep Database |
    while read databaseJson; do
        database=$(basename $databaseJson .json);
        echo "Updating database for $database";
        dotnet /HolismDotNet/Infra/DatabaseGenerator/bin/Holism.DatabaseGenerator.dll $PWD $databaseJson
    done 
    echo -e '\033[0;31m'"Wait for all responses! They will be shown, though this command seems to be finished";
}

UpdateDatabase