#!/bin/bash
    echo "Getting dependencies";
    if [ ! -f "$PWD/Dependencies" ]; then
        echo "There Isn't Dependency"
        return;
    fi

    while read Dependency; do  
    
        Org=$(echo $Dependency | cut -d'/' -f1)
        Repo=$(echo $Dependency | cut -d'/' -f2)     
    
        if [ -f "/$Org/$Repo/Database.json" ]; then
            cd /$Org/$Repo
            Generate  
            dotnet build               
        fi
    
        if [ ! -f "/$Org/$Repo/Database.json" ]; then        
            echo "There Isn't Database.json"    
        fi
    
    done <<< "$({ cat "$PWD/Dependencies"; echo; })"