version: "3.9"
services: 
    react:
        image: holism/react-dev:latest
        container_name: ${Organization}${Repository}
        ports:
            - "$RandomPort:3000"
        working_dir: ${RepositoryPath}
        volumes: 
            - /HolismReact/Infra:/Temp/Infra
            - /HolismReact/Panel:${RepositoryPath}/src/Panel
            - /HolismReact/Accounts:${RepositoryPath}/src/Accounts
            - ${RepositoryPath}/Logo.png:${RepositoryPath}/src/logo.png
            - ${RepositoryPath}:${RepositoryPath}/src/${Repository}
            - ${RepositoryPath}/.env:${RepositoryPath}/.env
            - ${RepositoryPath}/.env.test:${RepositoryPath}/.env.test
            - ${RepositoryPath}/.env.production:${RepositoryPath}/.env.production
            - ${RepositoryPath}/Resources.js:${RepositoryPath}/src/Resources.jsVolumeMappingPlaceHolder
        command: >
            sh -c
            "
            cd ${RepositoryPath}
            && if [ ! -d ${RepositoryPath}/node_modules ]; then ln -s /react/Infra/node_modules ${RepositoryPath}; fi
            && cp -a /Temp/Infra/. .
            && npm start
            "