FROM mariadb:latest
ENV PATH="${PATH}:/root/.dotnet/tools:/HolismHolding/Infra/SqlServer/Dev"  
ENV MARIADB_ROOT_PASSWORD=IC1joYMLZTT0fQMJ5qcz
USER root
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15

# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-get-started?view=sql-server-ver15