name: Build & Push holism/next-dev:latest

on:
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Get /HolismHolding/Infra
        run: |
          sudo mkdir /HolismHolding
          sudo chmod 777 /HolismHolding
          cd /HolismHolding
          git clone https://github.com/HolismHolding/Infra

      - name: Build holism/next-dev
        run: |
          cd /HolismHolding/Infra/Next/Dev
          docker build -t holism/next-dev:latest .
      - name: Push holism/next-dev
        run: |
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push holism/next-dev:latest
