name: Build & Push holism/dotnet-debugging:latest

on:
  workflow_dispatch:

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Get /HolismHolding/Infra
        run: |
          sudo mkdir /HolismHolding
          sudo chmod 777 /HolismHolding
          cd /HolismHolding
          git clone https://github.com/HolismHolding/Infra

      - name: Build holism/dotnet-debugging
        run: |
          cd /HolismHolding/Infra/DotNet/Debug
          docker build -t holism/dotnet-debugging:latest .
      - name: Push holism/dotnet-debugging
        run: |
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push holism/dotnet-debugging:latest
